apiVersion: apps/v1
kind: Deployment
metadata:
  name:  django-to-do
  labels:
    app:  django-to-do
spec:
  selector:
    matchLabels:
      app: django-to-do
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  django-to-do
    spec:
      containers:
      - image:  akshayraina/image_name:tag
        name:  django-container
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
kind: Service
apiVersion: v1
metadata:
  name:  django-to-do
spec:
  selector:
    app:  django-to-do
  type:  LoadBalancer
  ports:
  - name: http
    port:  80
    targetPort:  8000