apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  django-to-do
  labels:
    name:  django-to-do
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  django-to-do
    spec:
      containers:
      - image:  akshayraina/image_name:tag
        name:  django-container
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 10
      restartPolicy: Always
      imagePullPolicy: Always